config/routes.rb
Rails.application.routes.draw do
  mount Filepond::Rails::Engine, at: '/filepond'

  post 'home', to: 'home#update_avatar', as: :update_avatar
  delete 'home', to: 'home#destroy_avatar', as: :destroy_avatar

  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action :fetch_user

  def index; end

  def update_avatar
    @user.update(user_params)
    redirect_to root_path
  end

  def destroy_avatar
    @user.avatar.purge
    redirect_to root_path
  end

  private

  # We mock out our current user here by setting it as our first user
  def fetch_user
    @user ||= User.first
  end

  def user_params
    params.require(:user).permit(:avatar)
  rescue ActionController::ParameterMissing
    {}
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Filepond Demo</h1>

<p>
  Current User: <br />
  <b><%= @user.name %></b>
</p>

<p>
  Avatar: <br />
  <% if @user.avatar.attached? %>
    <%= image_tag(@user.avatar.variant(:thumb)) %>
    <br />
    <%= button_to 'Delete', destroy_avatar_path, method: :delete %>
  <% else %>
    No avatar
  <% end %>
</p>

<div>
  <%= form_with model: @user, url: update_avatar_path, method: :post do |f| %>
    <%= f.label :avatar, 'Update your avatar' %>
    <!-- We'll transform this input into a pond -->
    <%= f.file_field :avatar, class: 'filepond', direct_upload: true %>
    <%= f.button 'Update' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilepondRailsDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>